import { getArticlesByLanguage } from "./dbUtils";
import {
  getTopics,
  getGeneratedSubTopics,
  getRandomGeneratedTopics,
} from "./languageStorage";
import { TOPICS } from "./constants";

const getRandomItem = (array) => {
  return array[Math.floor(Math.random() * array.length)];
};

export function getPossibleSubTopics() {
  const selectedTopicIds = getTopics();
  if (!selectedTopicIds.length) return [];

  const generatedSubTopics = getGeneratedSubTopics();

  return selectedTopicIds.reduce((allSubTopics, id) => {
    const topic = TOPICS.find((t) => t.id === id);
    if (topic && topic.subTopics) {
      const filteredSubTopics = topic.subTopics.filter(
        (subTopic) => !generatedSubTopics.includes(subTopic)
      );
      return [...allSubTopics, ...filteredSubTopics];
    }
    return allSubTopics;
  }, []);
}

const RANDOM_TOPIC_TEMPLATE = `
**Examples of related topics to avoid**:
- If the topic is "Space Exploration," avoid related topics like "Mars Missions," "Astronaut Training," or "Space Technology."
- If the topic is "The Amazing World of Jellyfish", avoid topics like "The Enigmatic Beauty of Jellyfish"
- If the topic is "The History of Tea", avoid topics like "The Wonderful World of Tea"
- If the topic is "The Enchanting World of Bees", avoid topics like "The Intricate World of Bees"

**Examples of acceptable new topics**:
- "The Evolution of Classical Music"
- "Innovations in Renewable Energy"
- "The Cultural Impact of Social Media"
`;

function enhancePrompt() {
  const existingTopics = getRandomGeneratedTopics();
  if (!existingTopics?.length) return '';

  return `${existingTopics.join("\n")}\n\n
**IMPORTANT INSTRUCTION**: The topics listed above are already generated by you. Generate a completely new article with a unique topic that is NOT related to the above topics.**\n\n${RANDOM_TOPIC_TEMPLATE}`;
}

export function generateArticleCreationPrompt(customTopic = null) {
  if (customTopic === "Any Random Topic" || (!customTopic && !getPossibleSubTopics().length)) {
    const prompt = enhancePrompt();
    return {
      prompt: prompt + CREATE_CUSTOM_ARTICLE.replace("{{topic}}", '"Any Random Topic"'),
      topic: "Any Random Topic",
    };
  }

  if (customTopic) {
    return {
      prompt: CREATE_CUSTOM_ARTICLE.replace("{{topic}}", customTopic),
      topic: customTopic,
    };
  }

  const selectedSubTopic = getRandomItem(getPossibleSubTopics());
  return {
    prompt: CREATE_CUSTOM_ARTICLE.replace("{{topic}}", selectedSubTopic),
    topic: selectedSubTopic,
  };
}

export const CREATE_CUSTOM_ARTICLE = `
You are an experienced educator and content writer who specializes in creating engaging content in English.

Example (If the Topic is "Space Exploration"):
{
  "title": "The New Era of Mars Exploration",
  "summary": "Humans are closer than ever to reaching Mars with modern technology. Multiple space agencies are working together to make this dream a reality.",
  "imageKeywords": ["mars", "rocket", "astronaut", "spacecraft", "technology"]
}

Now, generate an article about {{topic}} using these rules:
1. If the topic is "Any Random Topic":
   - First, generate a unique and interesting topic
   - Choose from diverse fields like science, history, culture, technology, nature, etc.
   - Avoid common or generic topics
   - Make sure it's specific enough to be engaging
   - Example random topics:
     * "Underground Cities of the World"
     * "The Science of Bioluminescence"
     * "Traditional Games Across Cultures"

2. Generate an engaging and informative title:
   - Use simple, everyday English words
   - Avoid technical jargon or complex terms
   - Make it easy to understand for non-native speakers
   - Keep it clear and straightforward

3. Create a summary that is:
   - Written in simple, clear English
   - Uses basic vocabulary and common words
   - Avoids complicated sentences and fancy language
   - Easy to understand for all English levels
   - Exactly two sentences long
   - Factually accurate and engaging

4. Write in a friendly and engaging tone using natural English expressions

5. Provide exactly five single-word keywords ordered by relevance for Wikimedia image search:
   - Each keyword must be a single word in English only
   - Keywords should match the article's main theme and content
   - Order from most relevant to least relevant
   - Use common, searchable terms that would exist in image databases
   - Avoid abstract concepts that wouldn't have direct images

6. Return pure JSON without any markdown or code formatting

Return it in this JSON format:
{
  "title": "The title",
  "summary": "A two-sentence summary",
  "imageKeywords": ["keyword1", "keyword2", "keyword3", "keyword4", "keyword5"]
}`;

export const CREATE_ARTICLE_QUESTIONS = `
Generate 5 questions from the below article description with 4 options and answer. 

Article: "{{title}}"
Description: "{{content}}"

Return it in the following Array of JSON Objects format:
[
{"question":"question from the article",
    "options": ["A. Option1", "B. Option2", "C. Option3", "D. Option4"],
    "answer": "Answer for the question",
    "explanation" : "1 line explanation about the answer",
},
{"question":"question from the article",
    "options": ["A. Option1", "B. Option2", "C. Option3", "D. Option4"],
    "answer": "Answer for the question",
    "explanation" : "1 line explanation about the answer",
},
{"question":"question from the article",
    "options": ["A. Option1", "B. Option2", "C. Option3", "D. Option4"],
    "answer": "Answer for the question",
    "explanation" : "1 line explanation about the answer",
},
{"question":"question from the article",
    "options": ["A. Option1", "B. Option2", "C. Option3", "D. Option4"],
    "answer": "Answer for the question",
    "explanation" : "1 line explanation about the answer",
},
{"question":"question from the article",
    "options": ["A. Option1", "B. Option2", "C. Option3", "D. Option4"],
    "answer": "Answer for the question",
    "explanation" : "1 line explanation about the answer",
}
]
Please provide exactly five questions. Do not include any markdown or code formatting, only the pure array of JSON objects.
`;

export const GENERATE_ARTICLE_CONTENT = `
Generate an article content based on the following title and summary, adhering to the specified tone and length requirements.

Title: {{title}}
Summary: {{summary}}
Tone: {{level}}

Guidelines:
1. Total length: 120-160 words total, split into 2 paragraphs
2. Output Format: Return two paragraphs separated by "\n"
3. Adapt the writing style based on the tone:
   - easy/beginner: Simple words, short sentences, basic concepts
   - medium/intermediate: Moderate vocabulary, varied sentence structure
   - hard/advanced: Complex vocabulary, sophisticated expressions
   - children: Simple, fun, engaging for kids under 5
   - technical: Industry-specific terms, formal tone
   - creative: Descriptive, vivid, engaging language
   - conversational: Casual, friendly, using everyday language
   - academic: Scholarly, research-focused language
   - journalistic: Clear, concise, news-style writing
   
   If the specified tone is not listed above:
   - Analyze the tone name and context
   - Apply appropriate writing style that best matches the intended audience
   - Maintain clear and coherent structure
   - Focus on readability and engagement
   - Keep factual accuracy and professional quality

4. Keep content factually accurate and engaging
5. Return plain text only, using "\n" for paragraph separation

Example outputs:

For beginner:
The sun is very important for life on Earth. It gives us light and heat every day, helping plants grow and keeping us warm. The bright yellow star in the sky is like a giant lamp that never stops shining.\n Scientists have studied the sun for many years and learned amazing things about it. They found out that it is actually a huge ball of very hot gas, much bigger than our planet Earth. Even though it looks small from here, it's actually enormous!

For custom tone (storytelling):
Deep beneath the ocean's surface lies a world of wonder and mystery, where creatures of all shapes and sizes dance in the eternal darkness. Like tiny stars in a midnight sea, bioluminescent organisms create their own light, turning the deep waters into a natural light show that defies imagination.\n Among these remarkable inhabitants, the anglerfish dangles its glowing lure like a skilled fisherman, while transparent jellies pulse through the water like living glass sculptures. This hidden realm, untouched by sunlight, showcases nature's incredible ability to adapt and thrive in the most challenging environments.

6. Return the content without any additional formatting or metadata
`;

export const GENERATE_WORD_INFO = `
===== CRITICAL INSTRUCTIONS =====
1. THE INPUT "{{word}}" IS AN ENGLISH WORD
2. DO NOT TRANSLATE OR INTERPRET IT AS A WORD FROM ANY OTHER LANGUAGE
3. ALWAYS PROVIDE ENGLISH DEFINITIONS AND ENGLISH RESPONSES
==============================

You are an experienced English educator who specializes in clear and simple explanations.

Task: Generate comprehensive information for the English word: {{word}}

Rules:
1. For any word, no matter how short, always provide a valid English definition
2. For short words (3 letters or less):
   - Focus on the most common meaning in English
   - Use simple, clear definitions
   - Example for "tip": "the pointed or rounded end of something"
3. Provide a clear, concise definition suitable for learners
4. Include exactly 5 synonyms as a single string separated by " | "
5. Include exactly 5 antonyms as a single string separated by " | "
   - For words that lack direct antonyms, use conceptually opposite words
6. Create a simple example sentence that clearly demonstrates word usage
7. Use proper English and natural expressions
8. Return pure JSON without any markdown or code formatting

Examples:
{
  "word": "tiny",
  "meaning": "extremely small in size or amount",
  "synonyms": "minuscule | microscopic | miniature | minute | little",
  "antonyms": "huge | enormous | gigantic | massive | large",
  "exampleSentence": "The tiny ant carried a crumb of bread."
}

{
  "word": "up",
  "meaning": "toward a higher position or level",
  "synonyms": "upward | aloft | skyward | overhead | above",
  "antonyms": "down | below | downward | beneath | under",
  "exampleSentence": "The balloon floated up into the sky."
}
`;
